name: Delete Deployment Service
on: 
  push:
    branches:
     - 'releases/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run'
        type: environment
        required: true
      operation:
        description: 'Manula Operation'
        type: choice
        required: true
        options:
        - delete_layer_version
      layer_name:
        description: "Name of the Lambda Layer to delete versions"
        type: string
        required: true

jobs:
    delete_layer:
      if: ${{ github.event.inputs.operation == 'delete_layer_version' && github.event.inputs.layer_name != '' }}
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}
      permissions:
        id-token: write
      steps: 
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ap-northeast-1
        - name: Make Delete Layer Script Executable
          run: chmod +x .github/workflows/delete_layer.sh
        - name: Run Delete Script
          run: .github/workflows/delete_layer.sh "${{ github.event.inputs.layer_name }}"