name: Archive Zip Named Python
on: 
  push:
    branches:
     - 'releases/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests'
        type: environment
        required: true

jobs:
  deploy: 
    runs-on: ubuntu-latest
    needs: archive_library
    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Sample command
        run: aws s3 ls
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: python-app
      # - 
      # - name: Display downloaded files
      #   run: ls -lah
