name: Deploy
on: 
  push:
    branches:
     - 'releases/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run'
        type: environment
        required: true

jobs:
  call-zip-archive:
    uses: ./.github/workflows/zip_archive.yml
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    needs: call-zip-archive
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Upload Layer to AWS Lambda
        run: |
          aws lambda publish-layer-version \
            --layer-name test-layer \
            --compatible-runtimes python3.12 \
            --zip-file fileb://layer.zip
      - name: Display downloaded files
        run: ls -lah